# Generated by Django 2.2 on 2019-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('body', models.TextField(verbose_name='script body')),
                ('thumbnail', models.ImageField(upload_to='thumbs/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
