# Generated by Django 2.2 on 2019-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190517_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors_pictures/'),
        ),
    ]
