# Generated by Django 2.2 on 2019-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190715_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbs/'),
        ),
    ]
