# Generated by Django 2.2 on 2019-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190715_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
